//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Car_Insurance_Quotes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_car
    {
        public int Car_Id { get; set; }
        public int Car_Customer { get; set; }
        public int Car_Year { get; set; }
        public string Car_Make { get; set; }
        public string Car_Model { get; set; }
        public string Car_DUI { get; set; }
        public int Car_Num_Speed_Tickets { get; set; }
        public string Car_Coverage_Type { get; set; }
        public decimal Car_Quote { get; set; }
    
        public virtual tbl_customer tbl_customer { get; set; }
    }
}
